server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY  
  cloud:  
    gateway:
      routes:
        - id: AIRLINE-SERVICE
          uri: lb://AIRLINE-SERVICE
          predicates:
          - Path=/airline/**,/booking/**
          
        - id: FLIGHT-SERVICE
          uri: lb://FLIGHT-SERVICE
          predicates:
          - Path=/flight/**      

eureka:  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  